// <auto-generated />
using System;
using System.Collections.Generic;
using FileConverter.Data;
using FileConverter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileConverter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216115042_AddAssemblyAiAudioUrlToMediaItems")]
    partial class AddAssemblyAiAudioUrlToMediaItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileConverter.Models.BatchJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BatchJobs");
                });

            modelBuilder.Entity("FileConverter.Models.ConversionJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<AudioAnalysisData>("AudioAnalysis")
                        .HasColumnType("jsonb");

                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<List<KeyframeInfo>>("Keyframes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mp3Url")
                        .HasColumnType("text");

                    b.Property<string>("NewVideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VideoHash")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("ConversionJobs");
                });

            modelBuilder.Entity("FileConverter.Models.ConversionLogEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mp3Url")
                        .HasColumnType("text");

                    b.Property<double?>("ProcessingRateBytesPerSecond")
                        .HasColumnType("double precision");

                    b.Property<long?>("QueueTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("TotalSteps")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<string>("WaitReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("EventType");

                    b.HasIndex("JobId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("JobId", "Timestamp");

                    b.ToTable("ConversionLogs");
                });

            modelBuilder.Entity("FileConverter.Models.MediaStorageItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<AudioAnalysisData>("AudioAnalysis")
                        .HasColumnType("jsonb");

                    b.Property<string>("AssemblyAiAudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<List<KeyframeInfo>>("Keyframes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoHash")
                        .IsUnique();

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("FileConverter.Models.ConversionJob", b =>
                {
                    b.HasOne("FileConverter.Models.BatchJob", null)
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FileConverter.Models.BatchJob", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}

